export const SALE_LIST_REQUEST = "SALE_LIST_REQUEST";
export const SALE_LIST_SUCCESS = "SALE_LIST_SUCCESS";
export const SALE_LIST_FAIL = "SALE_LIST_FAIL";

export const SALE_DETAILS_REQUEST = "SALE_DETAILS_REQUEST";
export const SALE_DETAILS_SUCCESS = "SALE_DETAILS_SUCCESS";
export const SALE_DETAILS_FAIL = "SALE_DETAILS_FAIL";
export const SALE_DETAILS_RESET = "SALE_DETAILS_RESET";

export const SALE_CREATE_REQUEST = "SALE_CREATE_REQUEST";
export const SALE_CREATE_SUCCESS = "SALE_CREATE_SUCCESS";
export const SALE_CREATE_FAIL = "SALE_CREATE_FAIL";
export const SALE_CREATE_RESET = "SALE_CREATE_RESET";

export const SALE_UPDATE_REQUEST = "SALE_UPDATE_REQUEST";
export const SALE_UPDATE_SUCCESS = "SALE_UPDATE_SUCCESS";
export const SALE_UPDATE_FAIL = "SALE_UPDATE_FAIL";
export const SALE_UPDATE_RESET = "SALE_UPDATE_RESET";

export const SALE_DELETE_REQUEST = "SALE_DELETE_REQUEST";
export const SALE_DELETE_SUCCESS = "SALE_DELETE_SUCCESS";
export const SALE_DELETE_FAIL = "SALE_DELETE_FAIL";

export const SALE_COUPON_REQUEST = "SALE_COUPON_REQUEST";
export const SALE_COUPON_SUCCESS = "SALE_COUPON_SUCCESS";
export const SALE_COUPON_FAIL = "SALE_COUPON_FAIL";
export const SALE_COUPON_RESET = "SALE_COUPON_RESET";
